### ISSUE TITLE
abandoned typeof invariant

### ISSUE THREAD

**Issue by ljharb** [codehag/documenting-invariants#2]
> This was relaxed with value types.

Can you elaborate? I can't come up with a value where the typeofs agree but the ==/=== results don't. What "value types" are in the language?

**Comment by codehag** [comment]
I believe this was related to class syntax but I might have heard wrong, @erights would be able to clarify this

**Comment by codehag** [comment]
It should be partially clarified now.

**Comment by ljharb** [comment]
Thanks - that clarification suggests tho that it's not an abandoned invariant (because it still applies) but it's one that we're prepared to abandon if value types or operator overloading ever appear viable. (maybe i'm thinking about the word "abandoned" differently?)

**Comment by ljharb** [comment]
ah, i see "potentially", which addresses my final concern. Closing!
